Pry.commands.alias_command "c", "continue"
Pry.commands.alias_command "s", "step"
Pry.commands.alias_command "n", "next"
Pry.commands.alias_command "q", "quit"
Pry.commands.alias_command "w", "whereami"
Pry.commands.alias_command "ss", "show-source"
Pry.commands.alias_command "..", "cd .."
Pry.commands.alias_command "cl", "cd _"
Pry.commands.alias_command "cls", "cd _.class"
Pry.commands.alias_command "dp", "disable-pry"

